### ISSUE TITLE
Corrección en ETC.tsv

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#11]
L2752 "Ataque Rango" debería ser "Rango de ataque"
L2576 "¡Critico!" debería ser "¡Crítico!"
L4306 "Ratio Completo de Navegación" debería ser "Porcentaje de Navegación Completa"

"Remover" debería ser "Borrar" - Remover da a entender  que se mueve de nuevo

"Porfavor" debería ser "Por favor" 

"Ratio de crítco" -->> "Tasa de críticos" o "Probabilidad de críticos" || lo mismo pasa con Bloqueo

Todos los "Ratio" debería ser "Radio"
Ejemplo: "Ratio de ataque de area" -->> Radio de area de ataque

**Comment by Darkelfen** [comment]
Listo en 79859081534cff94051ef9bf15bfb83c1e0f2083
