### ISSUE TITLE
Corrección ETC.tsv 2

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#13]
L1581 {S20}{ol}{#46c8ff} No tienes suficientes PM
Debería ser "No tienes suficiente Resistencia"

**Comment by Darkelfen** [comment]
Listo en 79859081534cff94051ef9bf15bfb83c1e0f2083

Ahora quedó un No tienes suficiente Resistencia y No tienes suficientes PM
