### ISSUE TITLE
2 Traducciones de monstruos para ETC.tsv

### ISSUE THREAD

**Issue by Alex-GS** [TreeOfSavior-Spanish/Spanish-Patch#14]
Debido a traducción de objetos en ITEM.tsv ya he encontrado traducción para el nombre de dos monstruos pendientes en ETC.tsv
- ETC_20150714_011712 Brown Socket Archer => Arquero de Cuencas Marrones
- ETC_20150317_000516 Greentoshell => Corazaverde

La imagen del primer monstruo: https://i.gyazo.com/a5d5bb3c8733ff6f6afaf0da81c6046f.png
El segundo es un tipo bestia que dropea trozos de caparazón/coraza verdes: http://www.tosbase.com/database/items/668019/

**Comment by Darkelfen** [comment]
Listo en 7016272d29ea587fc8480af6fea365c2307e76a4
