### ISSUE TITLE
Error en Traducción de monstruo ETC 

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#15]
ETC_20150317_000399    Shadowgaler
Esta traducido como "Ruiseñor Sombrío" 
![Shadowgaler](https://cdn.discordapp.com/attachments/174667057218977792/175553258679435265/unknown.png)

Gale --> Significa  tormenta, vendaval, tempestad....

 por lo tanto la traducción debería ser algo Vendabal sombrio, Tormenta Sombria... o algo asi

**Comment by Darkelfen** [comment]
A este le había hecho una nota especial, pero no la encontré por ningún lugar.
Cuento corto: Tenía 2 opciones:
- Si era un mob que se asemejase a un ave; era un juego de palabras con Nightingale (Ruiseñor).
- Si era otro mob, era un nombre compuesto.

Opté por la primera opción al momento de traducirlo, pues sin ver el mob me hizo más sentido.

**Comment by Darkelfen** [comment]
Listo en 7016272d29ea587fc8480af6fea365c2307e76a4.

Quedó cómo "Tormentador Sombrío", razones en los comentarios del commit.

**Comment by Alex-GS** [comment]
Como sugirió Darkloud en Discord este nombre habría que reajustarlo un poco más. Propongo:
- Clamatormentas Sombrío
- Llamatormentas Sombrío

No se pierde la esencia del que crea el vendaval, pero tampoco resulta chocante como "Tormentador".

**Comment by Darkelfen** [comment]
ahora sí que si en ebebc5082e4b402191f75d9fb498acca7c42faff

**Comment by Darkelfen** [comment]
Re-abro, acabo de ver Clamatormentas Sombrío y en lo personal no me convence del todo.
Podríamos elaborarlo un poco más?

**Comment by Yokimitsuro** [comment]
A mi me convence muchisimo mas que ningún otro sinceramente yo lo dejaria asi

**Comment by Alex-GS** [comment]
Si quieres una traducción literal: "Shadowgaler" => "Vendavaladorsombrío"

Pero si lo adaptamos, tal y como hemos hecho, y revisas todas las posibilidades... Me parece que "Clamatormentas Sombrío" es perfecto. Shadow solo puede derivar en Sombra o Sombrío, porque para lo demás tenemos Black, Dark, Darkness, etc. Y no tenemos verbo en español del que sacar un agente para Galer, que viene de Gale => Vendaval. Si existiera sería **VENDAVALADOR**, siguiendo las normas del lenguaje más comunes. Como suena horrible, habría que irse al latín y darle vueltas al declinar "Vendaval".

No te "atormentes" más y déjalo como Clamatormentas Sombrío. Verás que es común y frecuente encontrarse Clamatormentas por el mundo de los MMORPG si lo buscas en Google: 

https://www.google.es/search?q=clamatormentas

**Comment by Darkelfen** [comment]
No me suena "natural", no me suena mal tampoco, sin embargo tampoco logro encontrar otro término mejor.

Realicé la búsqueda de "Clamatormentas" no es para nada común y me atrevería a decir que es "exclusivo" del lore de Warcraft, eso hasta que encontré esto:
https://www.rincondeldm.com/wiki/dungeons-dragons/lore/dioses/umberlee

Si D&D lo aprueba, lo apruebo.

**Comment by Yokimitsuro** [comment]
pues corrigelo y cierra :+1:
