### ISSUE TITLE
Correcciones ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#16]
tranportarte -> Transportarte

Tormentador Sombrío creo que habria que discutirlo queda fatal. Quizás Tormento Sombrío o Tormenta Sombría o Sombra Atormentada. La zona esta llena de Sombras Negras(enemigos).

**Comment by Darkelfen** [comment]
No logré encontrar tranportarte dentro del ETC.

Sobre "Shadowgaler" el asunto es conservar la inflexión "-r" del nombre. Pues da el sentido de "El que crea vientos/tormentas/tempestades de sombra/oscuridad" no que el mob es "un viento-sombra". Eso es importante a la hora de traducir el mob.

Le puse "Tormentador" pues no encontré otro equivalente más adecuado y que hiciera un juego de palabras, considerando que la palabra "galer" no existe en inglés, por ende de buscarle un origen sería algo cómo "the one who creates strong winds", en este caso no es un "galer" a secas, es un "shadowgaler", o sea "the one who creates dark winds". Para buscar un equivalente que cumpla la misma función, también usé una inflexión similar a "-r"; "-dor/-dora" o "-ero/era", y probé todas las combinaciones posibles:

Galerna -> Galernador / Galernero
Tormenta -> Tormentador / Tormentero
Tempestad -> Tempestador / Tempestero
Temporal -> Temporador / Temporalero
Vendaval -> Vendavalador / Vendavalero
Ventarrón -> Ventarroneador / Ventearronero
Viento -> Venteador / Venteadero

Aunque en lo personal me encanta la palabra Vendaval, y Vendaval Oscuro suena genial, reduce al mob sólo a una de sus creaciones, no sería un "shadowgaler", sería un simple "shadowgale" y perdería el sentido de "creador/fuente".

Luego, de todas las combinaciones hay una que suena parecido a una palabra en Español y es "Tormentador" que suena muy similar a "Atormentador" y cómo plus juega con las palabra de manera similar a cómo lo hace "Nightingale / Shadowgaler", que fue la traducción que le dí sin haber visto el mob. 

Si a "Atormentador", le quitamos la "a" queda "Tormentador", que si bien no existe en Español; Galer, tampoco lo hace en Inglés.

Edit: no tenía idea de la existencia de la palabra "Galerna".
"Ráfaga súbita y borrascosa de viento frío y húmedo en la costa septentrional de España; sopla entre el oeste y el noroeste y también afecta a la costa atlántica de Francia".

**Comment by Alex-GS** [comment]
"Llama Tormentas Oscuro" o "Clamatormentas Oscuro". No sería la primera vez que se utilizan esos nombres en la traducción de un juego. A unas malas "Tormentador Oscuro" tampoco es un mega-desastre.

**Comment by Yokimitsuro** [comment]
Clamatormentas me gusta, me parece d elos mas correctos.

**Comment by Alex-GS** [comment]
Lo he sugerido en el otro ISSUE y lo he re-abierto para que quede allí bien registrada la solución final: #15

**Comment by Darkelfen** [comment]
También me convence usar el prefijo "Clama-"

**Comment by Yokimitsuro** [comment]
sin el guión ni separación

**Comment by Darkelfen** [comment]
Sí, el - es para indicar un prefijo.

**Comment by Darkelfen** [comment]
listo en ebebc5082e4b402191f75d9fb498acca7c42faff
