### ISSUE TITLE
ETC ERROR

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#17]
En el juego sale que hay un error en esta linea, no la he comparado con la inglesa, pero dice que es en ETC_20150428_019121. este mensaje sale en una de las pantallas de carga.

ETC_20150428_019121    FAQ : Guarida{nl}1) Puedes cambiar el nombre de tu Guarida dandole click a "Configuración de Guarida". {nl}2) Puedes comprar aspectos para tu Guarida usando iCoins al darle click a "Cambiar Guarida".{nl}3) Puedes elegir el canal al que deseas ingresar desde tu Guarida.

**Comment by Alex-GS** [comment]
Esa línea en el original inglés:

ETC_20151224_019121 FAQ : Lodge{nl}1) You can change the name of your lodge by clicking "Lodge Settings".{nl}2) You can purchase Lodge skins using TP by clicking "Change Lodge".{nl}3) You can select a channel from the Lodge.

Parece bien traducida... ¿Podrías detallar más sobre el error? Tal vez una screenshot. Puede que sea algo de IMC o que tenga que ver con nuestras tildes no soportadas en las pantallas de carga.

**Comment by Darkelfen** [comment]
El error es el procesamiento de las "", deben ser ''.

**Comment by Darkelfen** [comment]
listo en ebebc5082e4b402191f75d9fb498acca7c42faff

Si eran ""

**Comment by Yokimitsuro** [comment]
![20160503163352_1](https://cloud.githubusercontent.com/assets/14833406/14986981/7805a84c-114e-11e6-8031-141352d5c38e.jpg)

Tienes que cambiarle "ETC_20150428_019121" por "ETC_20151224_019121"

**Comment by Yokimitsuro** [comment]
Cambia Icoins por TP y ya lo puedes cerrar al hacer el commit

**Comment by Darkelfen** [comment]
FnR
Icons -> TP
Ya arreglé esa línea.

**Comment by Darkelfen** [comment]
Línea lista en :https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/b66776e7f23c5288879eae256f00fb16a739b292

iCoins -> TP: https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/ef6d4d91180be4b6fdfb6a356a9490372420328d
