### ISSUE TITLE
Muertos Vivos En Fuga

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#18]
Creo que los DeadBorn Scap, Scap es un nombre propio y DeadBorn Podriamos dejarlo como No muerto o Muerto Viviente. 

En ningún momento veo el En fuga

**Comment by Alex-GS** [comment]
Deadborn => Nacido muerto => Podría aceptarse "Nonato"
Scap lo ha interpretado como "Scape", pero no es el caso.

"Scap Nonato" sería una buena traducción.

PD: El contexto de este monstruo según su lore, es que surge a partir de trozos amputados de otros Deadborn. Por lo cual no nace naturalmente, y ya nace muerto, pues son no-muertos.

**Comment by Darkelfen** [comment]
Suena a nombre de película, Scap lo interpreté cómo Scapee, my bad.
Listo en ebebc5082e4b402191f75d9fb498acca7c42faff
