### ISSUE TITLE
ETC => Error grave, Vubbe Fighter y Vubbe Warrior traducidos exactamente igual

### ISSUE THREAD

**Issue by Alex-GS** [TreeOfSavior-Spanish/Spanish-Patch#19]
Al parecer la traducción en ETC de Vubbe Fighter y Vubbe Warrior se ha realizado de la misma forma, por lo cual ahora no se puede distinguir a estos dos monstruos, a pesar de ser distintos.

INGLÉS => ETC_20150317_000048  Vubbe Luchador
ESPAÑOL => ETC_20150317_000048 Vubbe Luchador

INGLÉS => ETC_20150317_000555  Vubbe Warrior
ESPAÑOL => ETC_20150317_000555 Vubbe Luchador

Por fortuna el error de momento se limita a la línea 555 de ETC. Sin embargo, se debe tener en cuenta esto pues Vubbe Warrior y Vubbe Figther aparecen docenas de veces en otros textos de lore y nombres de objetos.

Sugiero "Guerrero Vubbe" y "Luchador Vubbe".

**Comment by Darkelfen** [comment]
Puse Vubbe Warrior cómo Vubbe Guerrero y Vubbe Fighter cómo Vubbe Luchador, se hizo FnR con lo mismo en ebebc5082e4b402191f75d9fb498acca7c42faff
