### ISSUE TITLE
Pequeñas correcciones

### ISSUE THREAD

**Issue by Darkelfen** [TreeOfSavior-Spanish/Spanish-Patch#2]
[UI - L774](https://github.com/TreeOfSavior-Spanish/Spanish-Patch/blob/Parche/Spanish/UI.tsv#L774) recividos -> recibidos
[UI - L1719](https://github.com/TreeOfSavior-Spanish/Spanish-Patch/blob/Parche/Spanish/UI.tsv#L1719) recivir -> recibir

[ITEM - L4](https://github.com/TreeOfSavior-Spanish/Spanish-Patch/blob/Parche/Spanish/ITEM.tsv#L4) Brzalete -> Brazalete

No logré encontrar donde esta el

"Me Gusta Recividos"

**Comment by Yokimitsuro** [comment]
Corregido
