### ISSUE TITLE
ETC => Traducción de "Black Maize" y "Charcoal Walker"

### ISSUE THREAD

**Issue by Alex-GS** [TreeOfSavior-Spanish/Spanish-Patch#20]
Dos traducciones de monstruos desde ITEM.tsv
- ETC_20150317_000880     Black Maize => Mazorca Negra (NdT: Literalmente sería "Maiz Negro", pero el bicho es más bien una mazorca, "cob", más fácil de leer y entender como Mazorca Negra / Mazorcas Negras)
- ETC_20151224_017760   Charcoal Walker => Caminante de Carbón

**Comment by Darkelfen** [comment]
En lugar de Mazorca, preferiría "Maíz", pues es más amplío que "Mazorca/Elote/Choclo" y muchos otros nombres que recibe el "Corn" al otro lado del charco.

Sobre Charcoal Walker, no estoy seguro de si hay una palabra especifica para referirse a alguien que camina sobre fuego/carbón. Si son imagianciones mías, caminante de carbón estaría bien (aunque suena a que es carbón andante, si es eso no habría problemas).

**Comment by Alex-GS** [comment]
De acuerdo, traduzcamos pues "Black Maize" como "Maíz Negro". Podría funcionar, al igual que "Ojo Negro" o "Mano Negra".

En el caso de Charcoal Walker se trata de un monstruo que es, literalmente, un pedazo de carbón andante. Llamarlo "Carbón Andante" sería otra posibilidad que no me atrae tanto. "Caminante de Carbón" suena un poco más esotérico, encima es la traducción directa y queda bien.

**Comment by Darkelfen** [comment]
Listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/42988133716d092587aec405f1b2acab5721ef4f
