### ISSUE TITLE
Errores de nombre en ITEM

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#22]
hay nombres de de pulseras por ejemplo (Bronza) que no esta traducido a Pulsera de Bronce.
Luego equipamiento que tiene el nombre delante por ejemplo Sirdgella Malla de Escamas, debería de ser Malla de Escamas Sirdgella.

**Comment by Darkelfen** [comment]
Yo dejaría Bronza, pues no es "Bronze" es "Bronza", sería nombre propio, a menos que se hayan equivocado en traducir el _kor.

**Comment by Yokimitsuro** [comment]
Bronza es bronce viene de otro idioma , del ruso

**Comment by Alex-GS** [comment]
Yo también lo dejaría como "Bronza". Es decir, no lo han traducido al inglés, han querido dejarlo como un nombre propio especial. Básicamente no intentaría traducir nada que no estuviera en inglés.

**Comment by Yokimitsuro** [comment]
pues no tocamos eso si queréis pero la posición del nombre del equipo si por favor >.<

**Comment by Alex-GS** [comment]
Si claro, el nombre de las piezas de equipo van ordenadas como dice Darkloud. Un ejemplo inventado:

Espada de Madera Artie
Maza de Madera Artie

**Comment by Yokimitsuro** [comment]
es que tu parte del archivo nose si es por FnR pero no esta ordenado xD

**Comment by Alex-GS** [comment]
Lo revisaré cuando vuelva a casa, estoy fuera un par de días. Mañana volveré.

**Comment by Alex-GS** [comment]
Debido a que no se ha encontrado el error que comenta Darkloud91 cierro ISSUE.
