### ISSUE TITLE
Radio del Área de Defensa (ETC)

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#23]
Radio del area de defensa esta traducido como Radio del area de ataque.

**Comment by Darkelfen** [comment]
estos 2 los regresaré a AoE Attack/Defense Ratio, porque no tenemos un consenso aún de cómo abordar este caso. La solución que le dí fue usar flecha arriba y flecha abajo, pero no creo funcione, podrías ponerme una SS porfavor.

**Comment by Yokimitsuro** [comment]
No entiendo, solo tienes que poner el de defensa como defensa para solucionar el problema ya que en las estadisticas de ven dos de ataque y no tiene sentido ya qur uno de ellos se refiere a defensa

**Comment by Darkelfen** [comment]
Quedó así:

ETC_20150317_002785 Radio de Ataques de Área
ETC_20150317_002786 Radio de Defensa a Ataques de Área

Original:
ETC_20150317_002785 AoE Attack Rate
ETC_20150317_002786 AoE Defense Rate

Si tienen una mejor traducción o comentarios respecto a estos 2 favor hacermelos llegar, no cierren este issue hasta que logremos definir bien eso por favor

**Comment by Yokimitsuro** [comment]
por que no.. 
Radio del Área de Ataque
Radio del Área de Defensa 
creo que queda mejor

**Comment by Alex-GS** [comment]
Tengo la respuesta a vuestras dudas :P 

AoE Attack Rate => Cupo de Ataque AoE
AoE Defense Rate => Cupo de Defensa AoE

**HAY QUE MEJORARLO**, pero es lo que significa. Os explico:
- AoE Attack Rate es el número de enemigos que se verán afectados por una habilidad de área. Cada habilidad tiene su propio AoE Attack Rate al que se le suma el del personaje (que es aumentado por equipamiento y buffs)
- AoE Defense Rate es el número de "cupos" que consume una habilidad de área al golper a este objetivo. Esta estadística es 1 por defecto en los jugadores y varía en los enemigos según sea pequeño, mediano o grande. Digamos que lanzo una habilidad con 6 AoE Attack Rate y golpea a un gigante con 3 AoE Defense Rate, en ese caso el consumirá 3 huecos y aún podré golpear a un máximo de 3 enemigos extras con la misma habilidad de área.

Ahora lo difícil, ¿cómo traducimos esto y que se entienda?

[http://wiki.tosbase.com/wiki/AoE_Attack_and_Defense_Ratio](url)

**Comment by Darkelfen** [comment]
Esa es la misma duda que tengo actualmente, el concepto en sí está enredado.

**Comment by Darkelfen** [comment]
ETC_20150317_002785 Amplitud de Ataque de Área
ETC_20150317_002786 Defensa contra Ataques de Área

**Comment by Darkelfen** [comment]
listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/b66776e7f23c5288879eae256f00fb16a739b292
