### ISSUE TITLE
Tasa de Bloqueo ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#24]
Si pones Probabilidad de Critico, pon todos con probabilidad de critico y haz lo mismo con Tasa de Bloqueo en L2754. no pongas algunos con tasa y otros con probabilidad
ETC_20150317_002754 Tasa de Bloqueo => ETC_20150317_002754  Probabilidad de Bloqueo

**Comment by Darkelfen** [comment]
Tengo una confusión acá porque se usan 2 términos distintos.

rate y chance / tasa y probabilidad respectivamente.

**Comment by Yokimitsuro** [comment]
tu estas usando uno para cuando te lo muestra en el arma y otro en las estadisticas

**Comment by Darkelfen** [comment]
Sí, en original 1 se muestra cómo rate y el otro cómo chance.
Mis dudas son las siguiente: 
- es la "probabilidad" de bloqueo n° o %?
- es la "tasa" de bloqueo n° o %?

en caso que ambas sean %, no tengo problemas en igualar "rate" y "chance" para que ambos sean tasa o probabilidad (en lo personal, optaría por tasa por ser más "corto").

En caso de ser distintos, creo debería quedar así, pues no sé a ciencia cierta si hay una diferencia entre estos 2 stats.

**Comment by Yokimitsuro** [comment]
yo creo que deberia ser lo mismo por que la estadistica que te sube no debe llamarse distinta osea yo me equipo una que me sube probabilidad y en estadisticas al equiparmela me aumenta la tasa, es raro... :S  yo dejaria probabilidad ya que se entiende mejor y no hay problemas de espacio

**Comment by Alex-GS** [comment]
En ambos casos es Probabilidad de Bloqueo. Utilizan chance y rate indistintamente para referirse al % de bloqueo. En español no es tan obvio si no se usa "Probabilidad".

**Comment by Darkelfen** [comment]
Ese punto lo entiendo, lo que no entendía era si por ejemplo uno era un % y el otro un número.
Ejemplifico:

Equipo:
Escudo de Madera
Probabilidad de Bloqueo +10.

En tus estadísticas:
Tasa de Bloqueo antes del escudo: 7%
Tasa de bloqueo después del escudo: 10%

En ese caso serían distintos, si ambos funcionan igual y no hay diferencia alguna, hago FnR en Tasa de Bloqueo a Probabilidad de Bloqueo.

**Comment by Darkelfen** [comment]
¿Hay más información o alguna confirmación respecto a esto?

**Comment by Yokimitsuro** [comment]
no he visto nada aun.

**Comment by Darkelfen** [comment]
ok, esperaré confirmación antes de

**Comment by Darkelfen** [comment]
Ya, finalmente he logrado descifrar esto.

Probabilidad y Tasa el concepto detrás de c/u es distinto.
Cómo siempre, miré en el _kor, para determinar si era uno u otro.

블럭 율 <-- Tasa de Bloqueo (el stat que se ve reflejado).

블락 확률 <-- Probabilidad de bloqueo
증가 <-- Aumentar

Lo que vemos acá es un buff o un diálogo (no lo se bien) pero a lo que se refiere es a precisamente que "bloquearas más fácil" no necesariamente un aumento en tu stat tasa de bloqueo.

**Comment by Yokimitsuro** [comment]
ok
