### ISSUE TITLE
L3576 ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#25]
ETC_20150317_003576 ¡A festejar! 
Deberia ser
ETC_20150317_003576 ¡Hagamos grupo! ya que se refiere a la descripción por defecto de los grupos.

**Comment by Darkelfen** [comment]
Gracias, solo decía "party!" así que lo tome cómo "fiesta".
y que tal "¡Vamos en Grupo!" ?

**Comment by Yokimitsuro** [comment]
tambien me parece bien

**Comment by Darkelfen** [comment]
Listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/b66776e7f23c5288879eae256f00fb16a739b292
