### ISSUE TITLE
L3591 a 3593 ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#26]
Tienes puesto DEX en vez de  DES en las lineas de ETC

**Comment by Darkelfen** [comment]
FnR

**Comment by Darkelfen** [comment]
listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/b66776e7f23c5288879eae256f00fb16a739b292
