### ISSUE TITLE
ETC => Traducción Algunos monstruos

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#27]
Crystal Spider => Araña de Cristal
Black Drake => Draco Negro
Green Drake => Draco Verde
Desert Chupacabra => Chupacabra del Desierto

**Comment by Darkelfen** [comment]
FnR, no logré encontrar el Draco verde

**Comment by Darkelfen** [comment]
Draco y araña listos en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/b66776e7f23c5288879eae256f00fb16a739b292
Desert Chupacabra listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/4a70bb1d9d5933756164f3bdc9515615e976bef1
