### ISSUE TITLE
nombre de Item

### ISSUE THREAD

**Issue by Darkelfen** [TreeOfSavior-Spanish/Spanish-Patch#29]
Piel de Lauzinute -> Caparazón de Lauzinute (es un escorpion).

**Comment by Yokimitsuro** [comment]
Se ha traducido de skin. Shell se usa como caparazón

**Comment by Darkelfen** [comment]
Así es, sin embargo en este caso no me fío de la traducción Inglesa pues la palabra coreana  "껍질" (kkeobjil) puede ser usada con las siguientes acepciones: 
- Shell
- Skin
- Husk

En este caso al ser el mob un Escorpion, corresponde que se emplee "Caparazón" en lugar de "piel" (lo mismo aplica para Zinute Skin) ya que los insectos no poseen piel sino que un "Caparazón".

**Comment by Yokimitsuro** [comment]
Reparado en 3d94fd1
