### ISSUE TITLE
ETC Removiendo

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#30]
Deberíamos cambiar Removiendo, por Quitando por que en castellano la acción removiendo significa mover.
![screenshot_20160506_00010](https://cloud.githubusercontent.com/assets/14833406/15087167/a75b13d0-13e6-11e6-81a2-86d84b67d07f.jpg)

**Comment by Darkelfen** [comment]
Haré un FnR respecto a este pues hay muchos "Remove", eso si, la RAE lo reconoce cómo sinónimo de quitar/apartar:
- Pasar o mudar algo de un lugar a otro.
- Mover algo, agitándolo o dándole vueltas, generalmente para que sus distintos elementos se mezclen.
- Quitar, apartar u obviar un inconveniente.

[Fuente](http://dle.rae.es/?id=VvbOqVK)

**Comment by Yokimitsuro** [comment]
pero queda fatal al igual que tirador aunque no con ese sentido.

**Comment by Darkelfen** [comment]
Dejó opciones:
- Conservar remove -> remover
- Quitando.
- Eliminando.
- Retirando.
- Sacando.

[Linguee](http://www.linguee.es/espanol-ingles/search?source=auto&query=remove)
[Word reference](http://www.wordreference.com/es/translation.asp?tranword=remove)

En lo personal prefiero Linguee pues muestra ejemplos "en contexto" y me ha ayudado en demasía.

**Comment by Yokimitsuro** [comment]
me gusta Retirando

**Comment by Darkelfen** [comment]
El problema es que sólo "removiendo" es factible para FnR, pero Retirando, Sacando, Quitando y Eliminando, se deben analizar caso a caso. ¿Tan horrible suena al otro lado del charco "removiendo"?

**Comment by Ayaros-Chan** [comment]
Remover suena bien para nosotros, pero quizá allá suene raro.
Retirar tampoco suena mal, pero la palabra también debería usarse según el contexto
no suena igual "sacar la corrupción" que "remover la corrupción" o "quitar la corrupción" 
incluso personalmente le pondría "Limpiar la corrupción" a mi parecer suena mas acertado.

**Comment by Darkelfen** [comment]
El problema es ese mismo, remover se adapta a retirar, eliminar, sacar o quitar, en cambio tendría que mirar el contexto de c/u de los remover presentes y ver si son retirar, eliminar, sacar o quitar y en ETC casi no hay contexto.

**Comment by Yokimitsuro** [comment]
igualmente los ingleses están mirando los contextos también, por que ya se han encontrado varias cosas raras xD. pero Remover-Retirando  creo que podria funcionar

**Comment by Darkelfen** [comment]
sin embargo no han tocado sus "remove", a eso me refiero.

**Comment by Yokimitsuro** [comment]
por que en ingles cuadra con todo, pero aqui creo que retirando funcionaria. ya que para maldiciones y esas cosas se usa la traduccion de release

**Comment by Darkelfen** [comment]
cerraré este.
