### ISSUE TITLE
ETC Tienes que consagrar la fuente de poder

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#31]
Deberia ser ¡Has consagrado la fuente de poder! ya que es lo que te pide la misión y lo haces 4 veces.
![screenshot_20160506_00009](https://cloud.githubusercontent.com/assets/14833406/15087187/d11c664c-13e6-11e6-87f3-f204ceb0fd78.jpg)

**Comment by Darkelfen** [comment]
Listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/d3825b2cde99e2b4a763f331f47ae5c7c6a76eab
