### ISSUE TITLE
QUEST _LV_0100 Corrección gramatical

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#33]
- En la linea 5 "QUEST_LV_0100_20150317_000005  Agh. ¡Andate! ¡No me hables! ¡Seremos capturados por los Vubbes!{nl}Este es mi lugar asi que vete." ¿Podríamos poner **"¡Vete!"** en vez de **"andate"**? ya que andate no está bien dicho ni se usa en España solo en los países de allí .
- En la linea 22 "QUEST_LV_0100_20150317_000022 Hmm... ¿Así de que eso se trata?{nl}Pareciera que simplemente destruyeron los suministros y se escaparon. Pero incluso si los{nl}Chupacabras tuvieran alas, seguramente no podrían hacer algo como eso.{nl}{nl}{nl}" **"Pareciera"** no esta bien dicho, se debería escribir **"parece"**
- Se vuelve a usar **"Pareciera"** en varias lineas..
- En la linea 39 "QUEST_LV_0100_20150317_000039 Muchas gracias, pero debes estar retrasado para otros asuntos.{nl}Además no podemos sólo sentarnos aquí y esperar. Planeamos seguir atacando." la frase **"pero debes estar retrasado para otros asuntos"** debe ser
  **"pero debes estar retrasando otros asuntos"**
- En la linea 44 "QUEST_LV_0100_20150317_000044 ¿No lo has visto?{nl}Entonces, en cual dirección podría haberse extraviado aquél débil y viejo compañero." la frase **"Entonces, en cual dirección podría haberse extraviado aquél débil y viejo compañero."** está mal traducida, debería ser **"Entonces, hacia que dirección podría haber deambulado ese débil y viejo compañero."**

**Comment by Darkelfen** [comment]
- Concuerdo en que ¡Andate! es una construcción propia del otro lado lado del charco. Sobre "¡Vete!" en lo personal habría usado ¡Alejate de mí! pues el NPC da una advertencia más que una orden.
- Sobre "pareciera", sólo concuerdo en que es el verbo correcto usado en un tiempo gramatical incorrecto; sin embargo "parece" tampoco es correcto pues se cambia la idea de la frase, lo correcto sería emplear "Al parecer" o "Aparentemente".
- L39, La construcción está correcta, pues es el personaje quien va con retraso; sin embargo me suena muy literal y a que el personaje tiene una imposibilidad mental, en lo personal emplearía "pero debes estar llegando tarde a atender otros asuntos".
- L44: which direction would that feeble old fellow have wandered off towards?
  Wander puede traducirse cómo deambular, sin embargo wander off es un "phrasal verb" y se traduce cómo "alejarse", "Old Fellow" puede traducirse directamente cómo "anciano" indicando una cierta cercanía del hablante. 
  "¿Hacia dónde se habría alejado ese anciano tan débil?"

**Comment by Yokimitsuro** [comment]
se sabe algo de @FrancoRiosP ?
