### ISSUE TITLE
QUEST _LV_0100 Error traducción

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#34]
En la linea 84, has dejado parte del texto en ingles y lo traducido deberías corregirlo.
- "QUEST_LV_0100_20150317_000084    Hey, rookie, are you on a break?{nl}Get some fat from Duckys in Lengvas Garden.{nl}{nl}Oye, novato, ¿Estás en descanso?{nl}Consigue algo de grasa de Duckys en Lengvas Garden."

De tal forma que quede así:
- "QUEST_LV_0100_20150317_000084    Oye, novato, ¿Estás descansando?{nl}Consigue algo de grasa de Duckys en Lengvas Garden."

En la linea 89 Corrige esta frase:
- "Por el momento está desorganizado aquí" => "Ahora mismo esto está desorganizado"

**Comment by FrancoRiosP** [comment]
En el primer texto no traduje los nombres propios porque Darkloud me dijo que hay quje dejarlos así por ahora :S

**Comment by FrancoRiosP** [comment]
Vale a la noche haré las correciones :)
