### ISSUE TITLE
Nombres de Mostruos

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#35]
Unicorn --> Unicornio
Scorpio --> Escorpión
Cerberus --> Cerbero
Minotaur --> Minotauro

**Comment by Darkelfen** [comment]
Unicorn ya está.
Scorpio -> FnR
Cerberus -> FnR
Minotauro ya está.

**Comment by Darkelfen** [comment]
listo en https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/5d4aea118841d0a23930fa1b9f7ef44229493ca7
