### ISSUE TITLE
ETC Benéfico

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#36]
Creo que en la L6073 "ETC_20150317_006074   Usa los álbumes para completar Colecciones que te{nl}den efectos benéficos" benéficos deberíamos de cambiarlo por "beneficiosos", benefico suena a algo de una organización que lucha contra algo  y creo que queda mucho mejor befeficiosos

**Comment by Darkelfen** [comment]
benéfico rae:
- adj. Que hace el bien.
- adj. Dicho de una cosa: beneficiosa.
- adj. Perteneciente o relativo a la ayuda desinteresada que se presta a los necesitados.

Creo que "beneficencia" es lo que suena a organización. Y benéficos suena más elaborado que "buenos".

**Comment by Yokimitsuro** [comment]
en que juego has visto tu estados benéficos? XD se usa beneficiosos y se entiende mejor por todo el mundo.

Rae: 
- adj. Provechoso, útil.

**Comment by Darkelfen** [comment]
No sabría decir allí, pues no estamos hablando de buff/debuff acá, sólo se está describiendo la colección; por otro lado, benéfico es más "corto" que beneficioso pero suena a colecta de caridad, tengo mis reparos en la construcción completa de esa parte, debo revisarla.
