### ISSUE TITLE
ETC Agriatada

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#37]
Agriatada => Agrietada

**Comment by Darkelfen** [comment]
Agriatada fue intencional.

"L21285 Receta - Ballesta Ligera Agriatada (Tratando de conservar el juego con Kracked)"

**Comment by Yokimitsuro** [comment]
no se suena fatal :-1:

**Comment by Darkelfen** [comment]
Considera que acá ""debe"" sonar fatal. Pues el error es intencional.
