### ISSUE TITLE
ETC Monstruos

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#38]
Shaman => Chamán
Mushcaria => Muscaria
Graveyard Golem => Golem de Cementerio
Grim Reaper => Segador Siniestro
Reaper => Segador
Ducky => Patito

**Comment by Darkelfen** [comment]
Agriatada fue intencional.

"L21285 Receta - Ballesta Ligera Agriatada (Tratando de conservar el juego con Kracked)"

**Comment by Darkelfen** [comment]
Graveyard Golem ya está: L375, Cuidado acá, hay cómo 5 tipos de golems distintos relacionados a cementerios.
Shaman -> Chamán FnR.
Grim Reaper -> Acá difiero, "The 'Grim Reaper' " es la personificación dada a la muerte con visión inglesa; algo similar a la personificación dada al frío con "Jack Frost". En mi opinión, debería usarse una personificación similar en lugar de traducir directamente acá.
Reaper -> Segador. FnR.
Ducky -> Patito. FnR.
Mushcaria: FnR.

**Comment by Darkelfen** [comment]
Graveyard Golem ya está: L375, Cuidado acá, hay cómo 5 tipos de golems distintos relacionados a cementerios.

Shaman -> Chamán FnR. Hago hincapié en que Shaman -> Chamán y no Featherfoot -> Chamán. En español no tenemos un término más que Kurdaitcha para referirnos tanto a la tribu cómo a su calzado al igual que el nombre de la skill.

Grim Reaper -> Acá difiero, "The 'Grim Reaper' " es la personificación dada a la muerte con visión inglesa; similar a la personificación dada al frío con "Jack Frost". En mi opinión, debería usarse una personificación similar en lugar de traducir directamente acá.

Reaper -> No existe a secas en ETC.

Ducky -> Patito. FnR.

Mushcaria: FnR. Propongo Mushcarfung traducir a "Amanita", (son Muscarias mini).

**Comment by Yokimitsuro** [comment]
ha esa personificación en España siempre se le ha llamado el segador

**Comment by Darkelfen** [comment]
Entonces en lugar de "Segador Siniestro" creo debería usarse "Segador" a secas, porque añadirle el siniestro lo hace sonar muy literal o qué tal "Segador de Almas"?

**Comment by Yokimitsuro** [comment]
Crystal Spider --> Araña de Cristal (Actualmente se las ve como Araña Cristal)
