### ISSUE TITLE
Errores en Quest.TSV

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#39]
- L29 "QUEST_20150317_000029    Tasa de 100 de plata.{nl}Es más barato que cortar a un monstruo por el centro." --> "QUEST_20150317_000029 La cuota es 100 de plata.{nl}Es más barato que cortar a un monstruo por el centro."
- "head commander" --> "Comandante principal" o "Comandante Jefe" tu tienes puesto comandante a la cabeza
- L44 Artículos -> Objetos 
- L65 "QUEST_20150317_000065    El Pokubu siempre ha estado aquí, pero a veces monstruos desconocidos son vistos también." --> "QUEST_20150317_000065 Los Pokubu siempre han estado aquí, pero a veces se ven monstruos desconocidos."
- L91 ¿donde abres el símbolo de exclamación?

**Comment by Yokimitsuro** [comment]
has corregido "Comandante en jefe", borra ese "en". cuando tengas todo corregido cierra este issue

**Comment by Yokimitsuro** [comment]
- L82 QUEST_20150317_000082 Bienvenido a la ciudad minera de Klaipeda!

Abre admiración

**Comment by Ayaros-Chan** [comment]
Pero Comandante Jefe no existe en español, el rango correcto es Comandante en Jefe.
No sé como se dirá en españa, pero aquí es Comandante en Jefe.

**Comment by Ayaros-Chan** [comment]
Corregido, cierro.
