### ISSUE TITLE
Error de Genero ETC.tsv

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#4]
ETC.tsv
L19891 "ETC_20151224_019892   [Señor de Orsha]{nl}    Inesa Hamondale" Debería ser "ETC_20151224_019892     [Señora de Orsha]{nl}    Inesa Hamondale"

**Comment by Darkelfen** [comment]
En este caso Señor es el título de Inesa, no que sea una Señora.
Lord of Orsha, intentaré encontrar un equivalente de genero neutral, porque Señora no suena a "Título"

**Comment by Yokimitsuro** [comment]
La palabra lord también tiene variante femenina, dado que no es aplicable a mujeres, por lo que en estos casos se opta por los términos “Dame” o “Lady”.

**Comment by Darkelfen** [comment]
Inglés: [Lord of Orsha]{nl}    Inesa Hamondale
Coreano: [오르샤 영주]{nl}이네사 해먼데일

영주: es Feudal Lord

**Comment by Yokimitsuro** [comment]
si, no te estoy diciendo que no sea un titulo, pero, más de una vez en series españolas que se basan en la época antigua a los Lord que son mujeres se les llama Señora  y  en este caso  "Señora de Orsha" se nota que es un titulo.

**Comment by Darkelfen** [comment]
Ok, en ese caso sí. El problema que me sucede es que "Señora" suena muy común (en extremo) y por la diferencia de contexto no se entiende que sea "importante". Sin embargo si se sub-entiende que es Título, no habría problema ;).

**Comment by Darkelfen** [comment]
Solucionado en 4a871ab66386cc44d3e7791624508c3b4a22bcd2

Señor -> Dama
(Dama me suena mejor que Señora)
