### ISSUE TITLE
Errores ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#40]
- {dia} -> {day}
  ![screenshot_20160515_00001](https://cloud.githubusercontent.com/assets/14833406/15271725/15abc01a-1a58-11e6-99a5-723d45c6944f.jpg)
- Recolectando seta o hongo( a mi parecer queda mejor seta  en este caso)
  ![screenshot_20160514_00002](https://cloud.githubusercontent.com/assets/14833406/15271727/192e856a-1a58-11e6-9ace-2a3b93ab8f98.jpg)
- Secondary phisical attack -> Ataque físico secundario
  ![screenshot_20160513_00002](https://cloud.githubusercontent.com/assets/14833406/15271728/1c1f6c62-1a58-11e6-82eb-d944f255c9e2.jpg)

**Comment by Darkelfen** [comment]
La primera hecho con FnR, habían 7 casos.

Las fotos 2 y 3 aún no he llegado a esas líneas.

**Comment by Yokimitsuro** [comment]
La 2 foto esta medio traducido queda raro xDsupongo que habra sido por FnR y la 3 creo que deberias traducirlo para dejar el cuadro de f1 totalmente traducido

**Comment by Darkelfen** [comment]
He ido haciendo varios FnRs en ETC, con palabras que no tienen cabida a interpretaciones ambiguas y hay centenares (literal) de frases a medias por eso mismo.
Contra: Quedan frases a medias.
Pro: ETC se avanza impresionantemente más rápido al ir haciendo FnR a conceptos que no pueden ser ambiguos.

Ya le hice FnR a Secondary Physical/Magical Attack, estaba por ahí por las 14000s más o menos.

**Comment by Yokimitsuro** [comment]
Cierro
