### ISSUE TITLE
shredded ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#41]
hay monstruos que eran "shredded" y los has traducido como despojos, ejemplo:
Demon Despojos --> Demonio Despedazado (No quedaria mejor)??

**Comment by Darkelfen** [comment]
El Shredded es un tipo de mob cómo un fantasma, en ese caso creo que debería ser:
Despojos Demoníacos o Despojos Endemoniado (según cómo se vea el mob).

**Comment by Yokimitsuro** [comment]
es un demonio encapuchado que flota. y no encuentro Despojo como traducción  de shredded, pero supongo que me vale ya que es algo despedazado.

**Comment by Ayaros-Chan** [comment]
Triturador Demoniaco, Triturador Endemoniado

**Comment by Darkelfen** [comment]
Triturador no es factible en este caso.

"Despojos" es la palabra que mejor conlleva la idea del mob en sí.
- Partes o elementos que quedan de algo después de haberlo usado o consumido.
- Cuerpo muerto de una persona o un animal, o parte que queda de él.

Obviamente no encontrarán traducción 1:1 de Shredded a Despojos ;)

La versión "pequeña" del mob es "Despojos", el "Demon" me deben indicar si lo interpreto cómo:
- Estatus o Profesion: Demonio Despojos.
- Característica: Despojos Demoníaco.

**Comment by Yokimitsuro** [comment]
queda mejor como acracterística
