### ISSUE TITLE
{día} por {day} y más.

### ISSUE THREAD

**Issue by Daniel4rt** [TreeOfSavior-Spanish/Spanish-Patch#42]
He estado observando que al parecer hicieron un remplazo total, pero afectó la palabra day por día en los curlys.

Recomiendo lo siguiente:

Remplazar
`{día`
`{day`

También tengan en cuenta que hay palabras como:
`{díaPLAYCOUNT}`

que deberían ser:
`{DAYPLAYCOUNT}`

Un saludo.

**Comment by Yokimitsuro** [comment]
Esta corregido para el próximo parche, muchas gracias! :+1:  cuando @Darkelfen  haga el commit cerrará esto

**Comment by Darkelfen** [comment]
De hecho, cuando envíe commit queda, mi ceremonia de titulo es mañana, por eso no he estado avanzando ETC últimamente.
