### ISSUE TITLE
Tablón de anuncios y "Probada" ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#43]
el objeto Tablón de anuncios en el juego se ve como --> "Tablón de anuncios." deberíamos quitarle el punto.

![screenshot_20160515_00002](https://cloud.githubusercontent.com/assets/14833406/15277602/e67f3b52-1b09-11e6-8b73-fd5ce6c42fc5.jpg)
En este caso probada -> ".. debo ..darle  un mordisco.." o ".. debo ..probarla..." añadiendo el debo en minusculas

**Comment by Ayaros-Chan** [comment]
Quitaré el punto

**Comment by Darkelfen** [comment]
Todos los tablones de anuncios en ETC están sin "."

"darle una... probada" lo cambiaré. Sin embargo poner debo en minúsculas sería un error gramatical.

Uso de puntos suspensivos:
- Se utilizan al final de una frase en lugar del punto, y con el mismo significado gramatical que este, si bien indican al lector que la frase precedente podría continuar. 
  No puedo aguantarme... (aunque debería)
- Para indicar la existencia en el discurso de una pausa transitoria que expresa duda, temor, vacilación o suspenso.
  Debo... darle una... probada.
