### ISSUE TITLE
Errores de traducción

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#44]
![screenshot_20160516_00005](https://cloud.githubusercontent.com/assets/14833406/15297667/9e8179e0-1b9b-11e6-8b4e-bd47a047f2bf.jpg)
- En esta foro en una de las misiones se refiere a Remolachas dulces no "betarragas dulces"

![screenshot_20160516_00004](https://cloud.githubusercontent.com/assets/14833406/15297706/d142692a-1b9b-11e6-8bc9-35195fd987f8.jpg)
- Creo que deberíamos intentar centrar ese Maestre Templario

![screenshot_20160516_00001](https://cloud.githubusercontent.com/assets/14833406/15297724/eb1f7d42-1b9b-11e6-88c4-491581899e1c.jpg)
- "pregutnar" -> preguntar
- esta hablando en masculino y es una chica

**Comment by Ayaros-Chan** [comment]
sobre la línea de la viuda indiferente, no sabía que era mujer, cambio seguro por segura ?

**Comment by Yokimitsuro** [comment]
si , por eso te lo reporto por que lo encontre :+1:

**Comment by Darkelfen** [comment]
"pregutnar" es mío, queda al siguiente commit. 

Aporto sobre las beterragas, la frase original es Sweet Beets, en ETC yo eliminé el "sweet" porque las "remolachas" en este lado del charco se usan para obtener azúcar; a diferencia de las beterragas que además de sonar extraño en el otro lado del charco (le pregunté a Thenestas que le sonaba más extraño si Beterraga, Betabel o Remolacha) se usan para ensalada.

Encuentro que para que coincida tanto en ETC cómo en QUEST debería quedar cómo "Remolachas" considerando que la remolacha ya es dulce por defecto.

Sobre el centrado, mejor dejarlo para más adelante, hay MUUUUUUCHOS NPCs por centrar.

**Comment by Rowleen** [comment]
En [Viuda Indiferente]. Sugiero que, quedaría mejor, en lugar de "seguro que las diosas no desaparecieron todas de una vez" cambiarlo por "seguro que las diosas no desaparecieron de golpe."

Y la pregunta, creo que lleva qué. Preguntar qué sucedió.

**Comment by Darkelfen** [comment]
No, ese que es un pronombre relativo y no un pronombre interrogativo.
