### ISSUE TITLE
Rubbed

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#45]
Estoy traduciendo "Rubbed" como "Calco" 
Rubbed Tool -> Herramienta de Calco
ITEM_20150317_003608    Primer Calco
ITEM_20150317_003609    Un calco del primer monumento de Lydia Schaffen
ITEM_20150317_003610    Segundo Calco
ITEM_20150317_003611    Un calco del segundo monumento de Schaffen
ITEM_20150317_003612    Tercer Calco
ITEM_20150317_003613    Un calco del tercer monumento de Lydia Schaffen
ITEM_20150317_003614    Cuarto Calco
ITEM_20150317_003615    Un calco del cuarto monumento de Lydia Schaffen
ITEM_20150317_003616    Quinto Calco
ITEM_20150317_003617    Un calco del quinto monumento de Lydia Schaffen

**Comment by Darkelfen** [comment]
yo igual, Rubbings -> Calcos/Calcando
