### ISSUE TITLE
cristales raíz del árbol o Tree Root Crystal

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#46]
Deberíamos de darle una traducción menos literal tal vez...
He visto la traducción cristales raíz del árbol y queda horrible o Cristal raíz del árbol, así que propongo:
- Raíz de Cristal

**Comment by Ayaros-Chan** [comment]
Suena mejor pero estas cambiando su significado ya que deja de ser la raíz de un árbol y puede ser raíz de una planta, de una flor, como lo es la flor del loto.
Propongo 
- Raíz del árbol de Cristal.

**Comment by Yokimitsuro** [comment]
la cuestión es que no estamos haciendo traducciones literales ya que mas de la mitad de los objetos van a necesitar cambiar de nombre y irá pasando con el tiempo, por que este juego tiene nombres rarisimos y con muchos adjetivos. que hay que hispanizar mas que traducir. pero que debe hacer poco a poco y con calma

**Comment by Ayaros-Chan** [comment]
En ese caso lo que propones estaría bien.

**Comment by Darkelfen** [comment]
Tree Root Crystal

el que se mencione "arbol" es importante, no puede ser omitido, el nombre completo sería

Divine Tree Root Crystal,

Cristal Raíz, efectivamente le cambia el significado total y completamente.

Veré cómo lo llevo en ETC y luego también dejaré opciones,

**Comment by Darkelfen** [comment]
Ya, acabo de revisar. En ETC estoy usando "Raíz Cristal del Árbol" y "Raíces Cristal del Árbol", sólo en L1955 se usa "Cristales Raíz". Al commit queda.

**Comment by Yokimitsuro** [comment]
Entonces como lo vas a dejar? por que no estoy de acuerdo con ninguna de esas 3 ultimas opciones

**Comment by Teravan** [comment]
Yo pondría Cristal de Raíz (se deduce que es de un árbol XD)

**Comment by Yokimitsuro** [comment]
pero eso no tiene sentido, al poner Cristal de Raíz estas diciendo que todas las raíces tienen cristales

**Comment by Teravan** [comment]
No entiendo la sinapsis de esa deducción. Puedo decir botón de chaqueta y no todas las chaquetas tienen botones...

**Comment by Darkelfen** [comment]
Ya, explico:
La frase se divide de la siguiente forma:
[ Tree ] [ Root ] [ Crystal ]
Lo importante es que es un "Crystal" eso **no puede ser cambiado**.

El siguiente elemento es "Tree Root", y es el que causa problemas.Sucede que esta construcción está "incompleta", cómo mencioné con antelación. A primera vista uno pensaría que "Root" es la idea central de esta parte de la frase. Si tomamos eso en consideración, lo correcto es traducirlo cómo "Cristal Raíz / Raíz Cristal / Raíz de Cristal / Cristal de Raíz"; sin embargo, de ser así los traductores habrían hecho lo mismo y sería sólo "Crystal Root o Root Crystal" y pero lo que observamos es "Tree Root Crystal"... Si seguimos en este nivel podemos estar estancados por años, así que recurriremos al lore del juego.

Dentro del juego hay un elemento **crucial** llamado "Divine Tree", si añadimos Divine, el elemento omitido en la traducción, el nombre completo es "[(Divine) Tree]  [Root] [Cristal]", esto lo traduje cómo
"Raíz (de) Cristal del Árbol (Divino)". La otra opción que barajaba en ese momento era "Cristal (de) Raíz del Árbol (Divino)", a mi consideración sólo esas 2 son opciones porque lamentablemente en esta clase de construcción, omitir un elemento es destrozar el lore del juego mismo.
- Raíz (de) Cristal del Árbol (Divino): Implica que todas las raíces del árbol son de cristal.
- Cristal (de) Raíz del Árbol (Divino): Implica que el cristal es parte de la raíz.

El "de" puede no ser omitido y añadirse sin problemas vía FnR. Sin embargo deben consultar el lore del juego para decidir si:
a) El árbol divino es de cristal.
b) Las raíces del árbol producen cristales.

**Comment by Darkelfen** [comment]
algún update en esto? opiniones?

**Comment by Yokimitsuro** [comment]
quisiera si tiene alguna relevancia en la historia, ya que es un simple objeto para recuperar Resistencia. Y si se puede hacer que quede bien en español usando por ejemplo el nombre que puse me gustaría que fuera así, si nadie responde preguntare a los traductores ingleses

**Comment by Darkelfen** [comment]
No sé que tan relevante sea un **ÁRBOL** en este juego...

De partida el juego se llama **TREE** of Savior.
Sale dibujado en una gran cantidad de mapas, mencionado por NPCs demasiadas veces y más encima aparece hasta en los sprite de clases.
![c_cleric_paladin](https://cloud.githubusercontent.com/assets/7315177/15728466/e7d48f26-2832-11e6-83cf-f5b3fe9dcc8a.png)
![cleric_f07](https://cloud.githubusercontent.com/assets/7315177/15728467/e7da7774-2832-11e6-9658-0b2e8af7eed7.gif)

**Comment by Yokimitsuro** [comment]
si pero me refiero al objeto en si, si hace falta que sea tan especifico el nombre si es TAN relevante en la historia el nombre de un objeto que apenas lo miras y solo usas para recuperar resistencia

**Comment by Darkelfen** [comment]
El asunto es que hay un límite de omisiones que puedes hacerle a algo sin deformar el sentido que quiere trasmitir. Lo importante a la hora de traducir es transmitirle a quien lee "el lore del juego", y "El Árbol (Divino)" si es un concepto importante a transmitir porque lo estarán viendo en cada momento y es un elemento omnipresente. El hecho que aparezcan en todos lados refuerza este hecho.

La máxima reducción que le veo es a:

"Cristal del Árbol", pues cubre los casos a y b, que mencioné anteriormente.

**Comment by Darkelfen** [comment]
alguna opinión en esto?

**Comment by Yokimitsuro** [comment]
Cristal del Árbol está bien a mi parecer

**Comment by Darkelfen** [comment]
'kay
