### ISSUE TITLE
Error de traducción

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#47]
Archivist Jonas --> Archivista (Archivero es un objeto o suena como tal)

Tienes una tarea que "cumplor" xD
![screenshot_20160520_00003](https://cloud.githubusercontent.com/assets/14833406/15441978/74857fa6-1ede-11e6-8982-6e88791e43c5.jpg)

**Comment by Yokimitsuro** [comment]
Corregido por mi, nadie asignado al archivo.

**Comment by Darkelfen** [comment]
Re-abro, rae Archivero:
Persona que tiene a su cargo un archivo, o sirve como técnico en él.
- http://dle.rae.es/?id=3Sn5CHV

El mueble se llama "Archivador".

**Comment by Yokimitsuro** [comment]
pero queda fatal en España, lo  cambie a Archivista, un sinonimo.

**Comment by Darkelfen** [comment]
'k FnR en ETC

**Comment by Darkelfen** [comment]
esto ya quedó en ETC. Cierro.
