### ISSUE TITLE
Dudas en Quest_LV_0100.tsv

### ISSUE THREAD

**Issue by Teravan** [TreeOfSavior-Spanish/Spanish-Patch#49]
**Línea 171: I am sure that you are qualified for this.{nl}Goddess Laima has led all these.**

Traducción provisional: Estoy seguro de que estás cualificado para esto.{nl}La Diosa Laima así lo ha dirigido.

He buscado que quedase mejor y no ponerlo literal, a ver si os convence a vuesas mercedes.

**Duda: ¿Spell = hechizo o Spell = conjuro?**

**Línea 194: No sé si hay traducción para "scattered materials"**

Un saludo.

**Comment by Darkelfen** [comment]
L194: Yo le puse Materiales "Desperdigados" o "Esparcidos" una de 2 en ETC...

L171: que tal: "La Diosa Laima así lo ha determinado"?

**Comment by Teravan** [comment]
En la L171 pensé en ponerle eso en primer lugar, pero cambia el significado de la frase en un matiz. Pone "Goddes Laima has led all these" que significa que nos ha guiado a nosotros para que esto sucediese, no que haya decidido que esto sucedería.

**Comment by Yokimitsuro** [comment]
Spell hechizo

**Comment by Darkelfen** [comment]
Sobre L171, traigo más información:

"Goddess Laima has led all these."

Comparé con lo más cercano que pude encontrar, 
"And you shall remember the whole way that the LORD your **God has led** you these forty years in the wilderness"
"Y te acordarás de todo el camino **por donde te ha traído** Jehová tu Dios estos cuarenta años en el desierto".

Creo que más que "dirigido" el concepto adecuado sería "guiado".
Algo así cómo "La Diosa Laima nos ha guiado hacia esto."

**Comment by Yokimitsuro** [comment]
donde esta Jehová en la frase? O_O "LORD" es el "SEÑOR" en sentido religioso

**Comment by Darkelfen** [comment]
Sentido religioso. Lo importante es lo último luego de eso.

> Creo que más que "dirigido" el concepto adecuado sería "guiado".
> Algo así cómo "La Diosa Laima nos ha guiado hacia esto."

Por cierto, lo copié textual de un antiguo testamento en inglés y uno en español.
Deutoronomio / Deutoronomy 8-2.
