### ISSUE TITLE
Correcciones en ITEM.tsv

### ISSUE THREAD

**Issue by Darkelfen** [TreeOfSavior-Spanish/Spanish-Patch#5]
L195: hroas -> horas
L198: Infierno y Cielo -> Cielo e Infierno (Es un Binomio como Black and White, en español Blanco y Negro, el orden está ligado a la velocidad a la cuál lo procesa el cerebro).

Al parecer  L1, L3, L10, L304, L407 y L488 son constantes, recomendaría revertir.

Creo que "Se puede leer" queda mejor cómo "Leíble", no sé que opinen al respecto.
(http://dle.rae.es/?id=N5ZAA9H)

Finalmente, en L110 Great Plant Cataclysm, yo traduje Plant cómo "Silvano" pues me pareció un sinónimo más adecuado que "de las Plantas", "Vegetal" o "Plantar".

**Comment by Yokimitsuro** [comment]
me parece bien todo, en cuanto llegue a casa hago el commit con las correcciones :)
