### ISSUE TITLE
Más Monstruos

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#50]
Stone Whale -> Ballena de Piedra
Slime -> Légamo
Blue Pawndel -> Pawndel Azul
Black Pawnd -> Pawnd Negro
Hogma Warden -> Guardián Hogma
Hogma Battle Boss -> Jefe de Batalla Hogma

**Comment by Darkelfen** [comment]
Stone Whale Esta traducido cómo "Ballena/Delfín de Roca". De roca le da más "solidez" al nombre del mob en lugar de "de piedra" que es traducción literal. Además de que Roca>Piedra.
Slime está traducido cómo "Limo".
Pawndels y Pawnds están en hiatus.
Hogmas están en hiatus.
Sólo tengo 1 caso de Hogma Combat Boss y es con un smart gen.

**Comment by Yokimitsuro** [comment]
y si deciden que haya un bicho con "Rock" también será de roca?  hay que tener esa distinción clara

**Comment by Darkelfen** [comment]
Veré la comparación entre infrorocktor y esos y la stone whale en _kr, luego traigo más información acá.

**Comment by Yokimitsuro** [comment]
estoy a ver si los añadimos en -> https://github.com/TreeOfSavior-Spanish/Spanish-Patch/wiki/3.-Monstruos y https://github.com/TreeOfSavior-Spanish/Spanish-Patch/wiki/3.1.-Monstruos-Jefe

**Comment by Darkelfen** [comment]
pasa a "de Piedra" 석화 (Stone) vs 락(Rock) "de Roca".

Sin embargo los mob "roca" Infrorocktor, Rocktortuga, etc. Quedarán cómo "roca".
No olvidar que tenemos en Hiatus la traducción de nombres de Mob a menos que salgan en un diálogo.

Ej:
¡Has fallado en derrotar a la Ballena de Piedra! {nl} Yekub se ha fortalecido

**Comment by Darkelfen** [comment]
Cierro hasta retomar la traducción de mobs.
