### ISSUE TITLE
ETC  Errores ultimo commit

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#52]
L1817 ¿Quieres aumentar {Stat} por Silver plata? -> ¿Quieres aumentar {Stat} por {Silver} plata?
L2528 El Brújula no responde -> La Brújula no responde

**Comment by Darkelfen** [comment]
Extraño hice 2 FnR para evitar ese problema.
- Plata -> Silver
- {Plata} -> {Silver}

No me tomó el último, de igual modo lo mando cómo commit urgente.
