### ISSUE TITLE
Actualización de archivos 30 de Mayo del 2016

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#54]
Aquí tenéis los cambios que hay que hacer a los archivos para el próximo parche. mirad si hay algo de vuestro archivo y cambiarlo.
https://github.com/TreeOfSavior-spanish/EnglishTranslation/commit/e76963ff1a2f55cac9acbd036555cbf9741d1043

Comentar por aquí cuando lo hayáis actualizado.

@Darkelfen @Corbi @Teravan @Ayaros-Chan @Xerraspls

**Comment by Teravan** [comment]
Actualizado

**Comment by Darkelfen** [comment]
Actualizado INTL y traducido.

**Comment by Corbi** [comment]
Hecho.

**Comment by Yokimitsuro** [comment]
Listo, queda ETC y se cierra.

**Comment by Darkelfen** [comment]
Actualizado ETC y traducido lo nuevo.
