### ISSUE TITLE
Traducciones Removiendo

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#55]
- ETC_20150317_002074   Purificando la contaminación
- ETC_20150317_002075   ¡El origen de la contaminación ha sido eliminado!

Creo que si pones purificando debería ser en ambos ya que Purificando es la acción y el otro es el mensaje que sale.
- ETC_20150317_001578   ¡Has fallado en comprar el objeto! El vendedor ha cancelado o sacado este objeto de la lista.

¡No se ha podido comprar el objeto! -> en mi opinión eso queda mucho mejor en español que has fallado, eso queda raro... y mas que sacado pondría quitado.
- ETC_20150317_002582   ¡Quitar Escudo!
- ETC_20150317_003226   Objeto equipado
- ETC_20150317_003227   Objeto quitado

Quizás podríamos traducirlo como "¡Desequipar Escudo! y "Objeto desequipado".
- ETC_20150317_004790   ¡Por favor deshaste la trampa que atrae monstruos!

Deshazte.
- ETC_20150317_005169   Círculo Mágico para Atar
- ETC_20150317_005169   Binding Magic Circle

Círculo Mágico de Unión. 
(Atar queda fatal, normalmente es solo usado para cuerdas o cordones) .
- ETC_20160520_021835   ¿Deseas cambiar tu clan a un estado no-neutral?{nl}Los clanes no-neutrales pueden participar en guerras.{nl}El estado no-neutral será mantenido por {DAY} día(s).

¿Deseas quitar el estado neutral a tu clan?{nl}Los clanes no neutrales pueden participar en guerras.{nl}El estado no neutral será mantenido por {DAY} día(s) -> Creo que quedaría mejor así.
- ETC_20160520_021829   Uso del Steam Inventory

Uso del Inventario de Steam

**Comment by Darkelfen** [comment]
ETC_20150317_002074 y ETC_20150317_002075
Hacen alusión a 2 objetos distintos y son 2 acciones distintas.
Si mal no recuerdo, purificas el pozo (estaba contaminado) y eliminas a Merregina (origen de la contaminación). "To remove" cubre ambas.

ETC_20150317_002582 y ETC_20150317_003227
Me parece perfecto. Vienen en camino cómo "Desequipar".

ETC_20150317_005169 Se necesita contexto antes de. Pues Unir y Atar si bien son sinónimos, tienen distintas connotaciones (inclusive opuestas).

Realmente no creo que suene tan fatal si consideras el siguiente ejemplo:
Se han unido en matrimonio (el matrimonio es algo bueno).
Le han atado en matrimonio (el matrimonio es algo malo).

ETC_20160520_021829 Tengo la duda si dentro de Steam mismo se llama Inventario de Steam o tiene otro nombre (lo pregunté hace 2 commits atrás).

**Comment by Yokimitsuro** [comment]
- ETC_20160520_021829
  ![captura](https://cloud.githubusercontent.com/assets/14833406/15728796/24556264-285f-11e6-922f-1fdeb0190265.PNG)
  Inventario de Steam
- ETC_20150317_005169
  ![screenshot_20160530_00001](https://cloud.githubusercontent.com/assets/14833406/15728810/4152f7dc-285f-11e6-8357-964b783a0f15.jpg)
  ![captura](https://cloud.githubusercontent.com/assets/14833406/15728854/7a44aa9a-285f-11e6-9552-6c996c22cae4.PNG)

Incluso podría ser  Círculo Mágico de Vinculación <-- Binding Magic Circle

Nota: "Le han atado en matrimonio" no entiendo esa frase, ya te dije que aquí atar se usa con cuerdas, cordones etc...

**Comment by Darkelfen** [comment]
ETC_20150317_001578
¡Imposible comprar el objeto! El vendedor ha cancelado o retirado este objeto de la lista.

Y por eso las maquinas no reemplazarán al hombre, aún...
Atar X a Y, es distinto a Unir X a Y.
![sin titulo](https://cloud.githubusercontent.com/assets/7315177/15728943/4595cd3e-2836-11e6-8d0b-7bfbcf082856.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/7315177/15729131/d4956ebc-2837-11e6-8e2d-ba622b5a9400.png)

![sin titulo3](https://cloud.githubusercontent.com/assets/7315177/15729306/579a99e4-2839-11e6-938a-8273928776b4.png)
![sin titulo4](https://cloud.githubusercontent.com/assets/7315177/15729311/5c3d7192-2839-11e6-85b7-2e0a412c3590.png)

En ese contexto y muy probablemente el contexto utilizado en este juego, la palabra correcta es "Atar".

**Comment by Darkelfen** [comment]
(Le di a close and comment por error)

**Comment by Yokimitsuro** [comment]
Entonces opino que la magia que tu llamas de atar es la que aqui se le dice vinculación como ua te dije aqui no se usa atar en ese sentido. Estamos empezando igual que con remover.

**Comment by Darkelfen** [comment]
Es distinto que con remover, pues según tengo entendido al otro lado del charco, le llaman "amarre". Que acá también se usa.

Nuevamente, amarre o atadura, no sólo se usa exclusivamente con "cuerdas".

http://amarratupareja.com/
http://www.conjurosyamarresdeamor.com/amarres.html
http://foro.enfemenino.com/forum/f79/__f15720_f79-Han-tenido-resultados-de-un-amarre-de-amor.html
http://amarresysolucionsentimental.jimdo.com/amarres-de-amor-efectivos-en-espa%C3%B1a/
http://amordedestino.com/
http://foro.enfemenino.com/forum/f79/__f15720_f79-Han-tenido-resultados-de-un-amarre-de-amor.html

**Comment by Yokimitsuro** [comment]
Aquí amarre se usa en otros términos no en esos, te estoy diciendo que queda fatal.  y sigo pensando que debería ser de "vinculación" o "unión".

**Comment by Darkelfen** [comment]
Creo que no revisaste las páginas que puse, pues son españolas; me preocupé de buscar páginas ESPAÑOLAS con Español de España precisamente por lo mismo .____.

**Comment by Teravan** [comment]
Respecto a eso último, casi nunca he visto "atadura". Lo más común en magia sería usar "vinculación", como bien dice Darkloud, o "ligadura", que se acerca más al significado que quieres darle, Darkelfen.

**Comment by Darkelfen** [comment]
Miren, no es algo que me este "inventando", solo no sabía que no era común, sin embargo favor ver las imágenes:

http://amarratupareja.com/wp-content/uploads/2016/04/amarres-de-amor-1.png

En esta página se usa "ligamento", pero la palabra en negritas es "amarre": http://www.conjurosyamarresdeamor.com/amarres.html

Acá lo dice en el título y en la página.
http://amarresysolucionsentimental.jimdo.com/amarres-de-amor-efectivos-en-espa%C3%B1a/

Nuevamente acá se refieren a "amarre" no ligadura:
http://amordedestino.com/

Esta dice "ligadura", sin embargo nuevamente menciona "amarre".
http://ligaduradeamor.com/

No logro comprender porque "amarre" les suena tan "fatal", si realmente se usa cómo traducción de "binding".
http://www.free-witchcraft-spells.com/binding-love-spells.html

Acá no me quiero referir a que la mob se vaya a enamorar o algo, me refiero a que el concepto de "amarre" cómo hechizo se aplica a la palabra "bind" en lugar de "ligadura" o "vinculación", en el libro lo encontré cómo "atadura" pero por lo que he visto se le conoce cómo "Amarre" casi universalmente.

Por otro lado, cómo mencioné anteriormente, tu no "unes/vinculas/ligas" un alma, la amarras/atas.

En ese sentido amarrar/atar, cubriría más la acción que estás realizando. Ya, recordé toda esa parte...

De partida en ese mapa la Diosa Saule se encuentra ENCERRADA en una jaula, si mal no recuerdo todo lo que haces en ese mapa va orientado hacia liberar las "zarzas" que están haciendo que?
Atando/Amarrando a saule dentro de su prisión. Tienes que destruir los 2 bichos que estaban manteniendo el hechizo. En esta parte Binding SE USA CÓMO AMARRE/ATADURA. Pues no la están uniendo a la prisión, ni están vinculando a Saule con la prisión; podría ser ligando, pero realmente ligando no suena muy extraño al otro lado del charco, porque casi suena a que Saule está voluntariamente allí...

**Comment by Darkelfen** [comment]
Al final quedó cómo de "unión", cierro.
