### ISSUE TITLE
Errores ITEM.tsv

### ISSUE THREAD

**Issue by Teravan** [TreeOfSavior-Spanish/Spanish-Patch#56]
- Línea 4085: Veneno **extraido** de un escorpión (falta la tilde).
- Línea 4097: Un rábano blanco maduro **recien** cogido de los campos. Se ve saludable, sin defectos (falta la tilde).
- Línea 4099: Madera de baja calidad arrancada de los vagones o cajas esparcidos a través de la granja. Puede **ser capaz de usada** para hacer algo útil (error sintáctico).
- Línea 4101: Un muñeco chamán, se dice que el Barón **de** lo **dió** a Arunas. Se dice que si se quema en un círculo mágico elimina el aura extraña (letra cambiada y un tilde sobrante).
- Línea 4103: Una botella vacía **de el** aprendíz de mago. Útil de diversas maneras.
- Línea 4104: Botella Llena con **Energia** de Monstruo (falta la tilde).
- Línea 4105: Una botella llenada con la **energia** de monstruos (falta la tilde).

**Comment by Yokimitsuro** [comment]
Lo corrijo cuando llege a casa.

**Comment by Yokimitsuro** [comment]
Listo
