### ISSUE TITLE
Issues ultimo commit ETC 

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#58]
https://github.com/TreeOfSavior-Spanish/Spanish-Patch/commit/87b266a108db754985fd4f22ebf4fd34956e9b34
- ETC_20150317_003655    ¡Has recolectado suficiente Grasa de Cocatriz Fat!
  te has dejado Fat
- ETC_20150317_004790    ¡Por favor deshazte la trampa que atrae monstruos!
  te falta el de
- ETC_20160224_020565    Cobrable hasta [{Time}] a ver si puedes dejarlo como -ETC_20160224_020565    Retirable hasta [{Time}]
  ya que habla de los objetos del correo

![screenshot_20160604_00002](https://cloud.githubusercontent.com/assets/14833406/15801737/e7136bb6-2a9e-11e6-92ec-b22efb0f65e7.jpg)
- Bolsa que contiene algo

creo que seria mas adecuado.

**Comment by Darkelfen** [comment]
Originalmente decía "pocket" no lo había visto in-game.

Pregunta que queda mejor Bolso Conteniendo Algo o Bolsa Conteniendo Algo, o realmente no hace diferencia?

**Comment by Yokimitsuro** [comment]
"Bolsa que Contiene Algo" queda mejor, Conteniendo suena muy mal al menos aqui en españa

**Comment by Yokimitsuro** [comment]
Traducido como "Mochila que contiene algo" -> cambiar a "Bolsa que contiene algo" y cerrar issue

**Comment by Darkelfen** [comment]
listo, cierro.
