### ISSUE TITLE
Hidden quest ETC

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#61]
Las líneas:
- ETC_20150317_002376   Primer espacio
- ETC_20150317_002377   Segundo espacio
- ETC_20150317_002378   Tercer espacio
- ETC_20150317_002379   Cuarto espacio

Hay que ponerles un espacio " " detrás ya que en el juego se lee "Primer espacio{num}" y debería verse "Primer espacio {num}"

**Comment by Darkelfen** [comment]
listo, cierro.
