### ISSUE TITLE
Remove ETC Comprensión

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#62]
![screenshot_20160607_00003](https://cloud.githubusercontent.com/assets/14833406/15875567/de7341a4-2d08-11e6-9b8e-a653b98e7f98.jpg)

Quitando -> liberando

![screenshot_20160607_00002](https://cloud.githubusercontent.com/assets/14833406/15875569/e11f35de-2d08-11e6-8e32-4cc32a07109e.jpg)

-eliminada en la misión deberia ser "liberada"

ya que se está liberando los sellos de la barrera.

**Comment by Darkelfen** [comment]
de no ser mucha molestia podrías ponerme los textos a corregir más grandes (soy corto de vista y no logro distinguir que es lo que apunta el issue).

**Comment by Yokimitsuro** [comment]
seria el de  la misión "**Missing Researches**"  "_Elimina la barrera oeste_" y  creo que las otras dos eran este y sur, debería cambiarse a  "_Libera la barrera oeste_" .
Y en la acción "_Eliminando_" pasarla a "_Liberando_"

**Comment by Darkelfen** [comment]
Recuerda que no hay orden lógico en ETC, pero ya cambié las barreras de eliminando a liberando.

**Comment by Darkelfen** [comment]
Queda pendiente la acción Eliminando -> Liberando
