### ISSUE TITLE
Leña

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#63]
![screenshot_20160606_00001](https://cloud.githubusercontent.com/assets/14833406/15877144/243b09f2-2d12-11e6-995e-eec9868ac902.jpg)

Recolectando ramas secas.

**Comment by Darkelfen** [comment]
Debería ser "Recolectaste Ramas Secas"
Me podrían reportar los azules con una joya y un signo más, que todos esos usan otro tiempo verbal.

Tengo 2 recolectando leña, dejé 1 y modifiqué otro.

**Comment by Darkelfen** [comment]
listo, cierro.
