### ISSUE TITLE
ETC -> Gravity Pole[URGE]

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#65]
Todos los "Gravity Pole" tienen que ser modificados a "Gravity Pull"

**Comment by Darkelfen** [comment]
listo, al commit va.

**Comment by Darkelfen** [comment]
Hold it, cual es el "real", pues veo que de "pull" han pasado a "pole" en el archivo "skill". 
Hay más información al respecto?

**Comment by Yokimitsuro** [comment]
https://github.com/Treeofsavior/EnglishTranslation/commit/f8b3e1f7243f5b1e9f4546194f90ac5b1ce76357

**Comment by Yokimitsuro** [comment]
Vale perdon me equivoque, queria ponerlo al reves Pole es el que tiene que estar
