### ISSUE TITLE
Correcciones en Quest.tsv

### ISSUE THREAD

**Issue by Darkelfen** [TreeOfSavior-Spanish/Spanish-Patch#7]
L24: jardín de flores superior -> en el jardín de flores más alto.
L25: aterrorizado -> aterrorizada (La Maestre Bokor es Mujer).
L26: Acá no estoy seguro del "encontrar", pues a esa altura ya te has "encontrado" con Uska, creo que "encontrarte con Uska", es más apropiado al contexto.
Sobre la traducción de Sir Uska, en lo personal usaría "Don Uska", porque señor me suena extraño.

**Comment by Yokimitsuro** [comment]
Sir es de caballero ya que es un paladín no de señor.

**Comment by Darkelfen** [comment]
También lo había pensado, pero no sé si la Maestre Bokor se refiere a Uskas cómo un Caballero o cómo un Don.

**Comment by Yokimitsuro** [comment]
habla de el como un paladin yo supondría que se refiere  a caballero. no imagino Don de ninguna forma

**Comment by Darkelfen** [comment]
Entonces, creo que L26 debería quedar más o menos así:

Bueno, deberías apresurarte y encontrar al señor Uska -> Bueno, deberías apresurarte y encontrarte con el Caballero Uska.

Considerando que el nombre del NPC es "Knight Commander Uska".

**Comment by Ayaros-Chan** [comment]
Por que no le dejan sin traducir? suena mejor Sir Uska, que Don Uska e incluso caballero Uska

**Comment by Ayaros-Chan** [comment]
Además todos saben lo que es Sir.

**Comment by Yokimitsuro** [comment]
Todos los Sir que hay de momentos se refiere a caballero así que se traducirá como tal

**Comment by Ayaros-Chan** [comment]
Pero Uska no es solo un caballero, es un comandante también, por lo que debería ser Comendador Uska.

Comendador = Knight Commander.
aunque si todos los "Sir" deben ser caballeros, pues ni modo.

**Comment by Yokimitsuro** [comment]
hay momentos en los que pone "Knight Commander", esta traducido como comandante de los caballeros y donde pone Sir se traduce como "caballero"

**Comment by Ayaros-Chan** [comment]
Suena raro que se haya traducido así.
http://dle.rae.es/?id=9up2Lqa
pero lo tendré en cuenta a la hora de ver algún Sir.

**Comment by Yokimitsuro** [comment]
@Ayaros-Chan  sigues viva? no se te ve por discord ni  activa en el proyecto
