### ISSUE TITLE
ETC errores 09/06/2016

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#70]
- Absorver -> absorber
- ETC_20151102_016573   Fight against Señor Demonio Zaura who imPrisióned Diosa Lada
- ETC_20151224_017674   ImPrisióned Infrogalas Arquero
- ETC_20151224_018350   Prisióner Waiting Room
- ETC_20151224_018490   ImPrisióned Laima

Imprisióned xD es de un FnR, reparalo.

**Comment by Darkelfen** [comment]
Quedaron (con un segundo FnR)
Combate al Señor Demonio Zaura quien aprisionó a la Diosa Lada
Arquero Infrogalas Aprisionado*
Sala de Espera de los Prisioneros
Laima Captiva
