### ISSUE TITLE
Monstruo Operor

### ISSUE THREAD

**Issue by Yokimitsuro** [TreeOfSavior-Spanish/Spanish-Patch#71]
**_Operor_** se ha traducido como **_Operador_**. pero **_Operor_** viene del latín y significa Trabajar. aunque no veo bien la traducción de trabajador.

**Comment by Liaths** [comment]
Si lo tomamos como que viene del latín, tendría sentido que se llamaran "trabajador", ya que son una especie de abeja/avispa en el juego o: y bueno, todos sabemos que tenemos abejas obreras y cosas...

**Comment by Darkelfen** [comment]
y "operario"?
revisaré _kor por si las dudas

**Comment by Yokimitsuro** [comment]
operario lo veo fatal para una abeja :/

**Comment by Darkelfen** [comment]
Bueno, primero que todo debo discrepar en que _operor_ venga de algo, pues no existe cómo palabra. **Operator** sería la palabra correcta.

Por otra parte,  _kor no nos provee de mayores pistas:
오페러 (Opela) -> Operor / Opera.

Considerando el error al escribir la palabra, Operor nos sirve pues si eliminan las negritas en Inglés o español queda Operor:
Oper**ad**or -> Operor.
Oper**at**or -> Operor.

Si aplicamos el mismo razonamiento a "Trabajador", el nombre debería ser
Trabaj**ad**or -> Trabajor.

Por eso, encuentro más razonable que se llame "Operor".

**Comment by Yokimitsuro** [comment]
https://es.glosbe.com/la/es/operor

y entonces deberías cambiarle el nombre tu ya que fuiste el que le pusiste operador.

**Comment by Darkelfen** [comment]
ya está hecho :v:
